#!/usr/bin/env python3
"""Convert an 8-pixel-wide BDF font into a C glyph table for the kernel console.

Usage: bdf2c.py FONT.bdf LICENSE_FILE > kernel/src/dev/font.c

Only printable ASCII (0x20-0x7e) is kept. Each glyph is `height` bytes, one per
row, most significant bit = leftmost pixel.
"""
import sys


def parse_bdf(path):
    glyphs = {}
    width = height = descent = None
    with open(path) as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("FONTBOUNDINGBOX"):
            width, height, _, yoff = map(int, line.split()[1:])
            descent = -yoff
        elif line.startswith("ENCODING"):
            code = int(line.split()[1])
        elif line.startswith("BBX"):
            bw, bh, bx, by = map(int, line.split()[1:])
        elif line == "BITMAP":
            rows = [int(next(lines), 16) for _ in range(bh)]
            cell = [0] * height
            top = (height - descent) - (by + bh)
            for i, row in enumerate(rows):
                # BDF rows are padded to whole bytes; shift into an 8-bit row.
                nbytes = (bw + 7) // 8
                value = row >> (nbytes * 8 - 8) if nbytes > 1 else row
                if 0 <= top + i < height:
                    cell[top + i] = (value >> bx) & 0xFF
            glyphs[code] = cell
    if width != 8:
        sys.exit(f"{path}: only 8-pixel-wide fonts are supported")
    return height, glyphs


def main():
    bdf, license_file = sys.argv[1], sys.argv[2]
    height, glyphs = parse_bdf(bdf)
    with open(license_file) as f:
        license_text = f.read().strip()

    print("/* Generated by tools/bdf2c.py from " + bdf.split("/")[-1] + ". Do not edit.")
    print(" *")
    for line in license_text.splitlines():
        print((" * " + line).rstrip())
    print(" */")
    print()
    print("#include <stdint.h>")
    print("#include <vexa/font.h>")
    print()
    print(f"const uint8_t font_glyphs[FONT_GLYPH_COUNT][FONT_HEIGHT] = {{")
    for code in range(0x20, 0x7F):
        cell = glyphs.get(code, glyphs.get(ord("?")))
        label = "'\\\\'" if code == 0x5C else "'\\''" if code == 0x27 else f"'{chr(code)}'"
        print(f"    /* {label} */ {{" + ", ".join(f"0x{b:02x}" for b in cell) + "},")
    print("};")


if __name__ == "__main__":
    main()
